export const FETCH_WEATHER_INFO_SUCCESS = "FETCH_WEATHER_INFO_SUCCESS";
export const REFRESH_WEATHER_INFO_SUCCESS = "REFRESH_WEATHER_INFO_SUCCESS";
export const REFRESH_WEATHER_START = "REFRESH_WEATHER_START";


